CUISINE_DISHES = {
    "Indian": [
        "Cabbage Sabzi",
        "Aloo Gobi",
        "Vegetable Korma",
        "Palak Paneer",
        "Vegetable Pulao",
        "Cabbage Paratha",
        "Mixed Veg Curry",
        "Vegetable Upma",
        "Veg Manchurian",
        "Vegetable Sambar",
        "Cabbage Pakora",
        "Veg Biryani",
        "Vegetable Thepla",
        "Veg Kurma",
        "Cabbage Thoran",
        "Veg Khichdi",
        "Veg Handi",
        "Vegetable Poha",
        "Veg Stew",
        "Vegetable Cutlet"
    ],

    "French": [
        "Ratatouille",
        "Vegetable Quiche",
        "French Onion Soup",
        "Gratin de Legumes",
        "Vegetable Crepes",
        "Soupe de Choux",
        "Vegetable Tart",
        "Provencal Vegetables",
        "Stuffed Cabbage Rolls",
        "Vegetable Souffle",
        "Vegetable Nicoise",
        "Braised Cabbage",
        "Vegetable Veloute",
        "French Veg Stew",
        "Vegetable Terrine",
        "Vegetable Cassoulet",
        "Veg Croquettes",
        "Vegetable Galette",
        "Veg au Gratin",
        "Vegetable Potage"
    ],

    "Mexican": [
        "Veg Tacos",
        "Veg Quesadilla",
        "Vegetable Burrito",
        "Veg Enchiladas",
        "Veg Fajitas",
        "Mexican Veg Soup",
        "Veg Nachos",
        "Veg Chimichanga",
        "Veg Tamales",
        "Mexican Rice Veg",
        "Veg Tortilla Wrap",
        "Veg Chilaquiles",
        "Veg Pozole",
        "Veg Tostadas",
        "Veg Flautas",
        "Veg Mole",
        "Veg Empanadas",
        "Veg Salsa Bowl",
        "Veg Calabacitas",
        "Veg Elote Bowl"
    ],

    "Thai": [
        "Thai Veg Green Curry",
        "Veg Pad Thai",
        "Veg Thai Fried Rice",
        "Veg Tom Yum Soup",
        "Veg Massaman Curry",
        "Veg Red Curry",
        "Veg Basil Stir Fry",
        "Veg Spring Rolls",
        "Veg Thai Noodles",
        "Veg Coconut Soup",
        "Veg Larb",
        "Veg Panang Curry",
        "Veg Yellow Curry",
        "Veg Thai Salad",
        "Veg Drunken Noodles",
        "Veg Sticky Rice",
        "Veg Thai Stew",
        "Veg Satay",
        "Veg Papaya Salad",
        "Veg Khao Soi"
    ],

    "Korean": [
        "Kimchi Cabbage Pancake",
        "Veg Bibimbap",
        "Veg Japchae",
        "Veg Kimchi Stew",
        "Veg Kimbap",
        "Veg Korean Fried Rice",
        "Veg Tteokbokki",
        "Veg Mandu",
        "Veg Bulgogi Bowl",
        "Veg Korean Soup",
        "Veg Doenjang Jjigae",
        "Veg Kimchi Noodles",
        "Veg Korean Pancake",
        "Veg Gochujang Stir Fry",
        "Veg Bossam Style",
        "Veg Banchan Platter",
        "Veg Jajangmyeon",
        "Veg Sundubu",
        "Veg Korean Hotpot",
        "Veg Rice Bowl"
    ]
}

__all__ = ["CUISINE_DISHES"]
